### PR TITLE
DO NOT MERGE: Test astropy 4.1.rc1

### PR DESCRIPTION
**Pull request by pllim**
Test astropy 4.1.rc1.

Err... I hope this works. That template thing doesn't say how to pin astropy.

### CODE REVIEW

**Comment by pllim** [comment]
I don't see how the failure is related to astropy 4.1rc1. Maintainers should advise.
```
E   ModuleNotFoundError: No module named 'wcsaxes'
```

**Comment by astrofrog** [comment]
Thanks! Issues fixed in https://github.com/astropy/reproject/pull/234 - waiting to see if the CI passes there, and once it's merged can you rebase this, and also pin sunpy to be 2.0rc2?

**Comment by astrofrog** [comment]
@pllim - this can now be rebased - and please include the pinning for sunpy too as mentioned above.

If only the 32-bit and wheel builds fail, we're all good (those are unrelated to astropy 4.1rc1)

**Comment by pllim** [comment]
Things are failing with `docker: Error response from daemon: Get https://quay.io/v2/pypa/manylinux2010_i686/manifests/latest: received unexpected HTTP status: 500 Internal Server Error.`

**Comment by pllim** [comment]
I rebased. Now it is failing with `TypeError: cannot compare: objects must have equivalent frames: <HeliographicStonyhurst Frame (obstime=2011-02-15T00:00:00.340)> vs. <HeliographicStonyhurst Frame (obstime=2011-02-15T00:00:00.340)>` -- Is this related to astropy 4.1rc1?

**Comment by pllim** [comment]
@astrofrog , docs and sdist failed too. Is this a 🟢 or 🔴 ?

**Comment by pllim** [comment]
@astrofrog , you should rerun this with 4.1rc2, just in case.

**Pull request closed without merging**
