### PR TITLE
General maintanance

### PR DESCRIPTION
**Pull request by bsipocz**
In addition of switching to use standalone six, now I'm pushing more maintenance related commits to this PR.

### CODE REVIEW

**Comment by bsipocz** [comment]
Failures are unrelated and preferably should be addressed in another PR.

**Comment by bsipocz** [comment]
we should also enable cron jobs on travis, so it's easier to keep track the status of the master branch. @astrofrog - you're the only one having the power to do that

**Comment by bsipocz** [comment]
Docs  is building locally with the helpers 2.0.10, so it should be fixed when #176 is merged. I'm not sure though about the astropy build errors, have to look at them more closely a bit later.

**Comment by bsipocz** [comment]
Rebased, this should now pass CI.

**Comment by astrofrog** [comment]
Trying to work around the ci failures - see https://github.com/astropy/ci-helpers/issues/394 for a description of the problem. No time to investigate at the moment so just doing the easiest fix here.

**Comment by bsipocz** [comment]
@astrofrog - Oops, that was an oversight of not cleaning things up properly.

**Pull request merged**
